version: '3'
services:
  #Flutter Web Boilerplate
  ppcb_web:
    container_name: ppcb_web
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 8080:80
    volumes: 
      - ./:/ppcb_web
    tty: true
    environment: 
      - TZ=Asia/HoChiMinh
    networks:
      - api-network

#Docker Networks
networks:

  api-network:
    driver: bridge