version: '3'
services:
  #Flutter Web Boilerplate
  web_bloc_boilerplate:
    container_name: web_bloc_boilerplate
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 8080:80
    volumes: 
      - ./:/web_bloc_boilerplate
    tty: true
    environment: 
      - TZ=Asia/HoChiMinh
    networks:
      - api-network

#Docker Networks
networks:

  api-network:
    driver: bridge