on:
  push:
    branches:
      - staging

jobs:
  release-android:
    name: Build and release Android app
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.x"

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Update Flutter dependencies
        run: flutter clean && flutter pub get

      - name: Install Fastlane
        run: cd android && bundle update --bundler && cd ..

      - name: Execute Fastlane command
        run: cd android && fastlane android staging

  release-ios:
    name: Build and distribute IOS app to TestFlight
    env:
      VIVI_API_KEY: ${{secrets.VIVI_API_KEY}}
      CERTIFICATE_DISTRIBUTION: ${{secrets.CERTIFICATE_DISTRIBUTION}}
      SIGNING_KEY_FILE_PATH: "/Users/runner/work/vivi/vivi/ios/signing-cert.p12"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Update Flutter dependencies
        run: flutter clean && flutter pub get

      - name: Decode signing certificate into a file
        run: echo '${{env.CERTIFICATE_DISTRIBUTION}}' | base64 --decode > ${{env.SIGNING_KEY_FILE_PATH}}

      - name: Install Fastlane
        run: cd ios && gem install cocoapods && pod install && cd ..

      - name: Execute Fastlane command
        run: cd ios && fastlane ios staging
